site_name: Kornet
theme: 
  logo: logo/logo_white.svg
  features:
    - navigation.instant
    - navigation.sections
    - content.tabs.link
  name: material
  icon: 
    repo: fontawesome/brands/github
    # logo: fontawesome/solid/chess-knight
  palette:
    scheme: slate
    primary: light blue
    accent: cyan

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

repo_url: https://github.com/subatiq/kornet
repo_name: subatiq/kornet